project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    toc: true
    html-footer: "_partials/custom-footer.html"

editor: visual

execute: 
  freeze: auto
  